[project]
name = "reassembly-basic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib==3.10.3",
    "open3d==0.19.0",
    "trimesh==4.6.9",
]
